services:
  postgres:
    container_name: postgres-container-indicium
    image: postgres
    environment:
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
      POSTGRES_DB: northwind
    ports:
      - "5432:5432"
    networks:
      - backend

  my_db:
    image: mongo
    container_name: mongo-container-od0g
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dharma
      MONGO_INITDB_ROOT_PASSWORD: 4815162342
    volumes:
      - ./dbmongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  airflow:
    image: puckel/docker-airflow:1.10.9
    container_name: airflow-container
    restart: always
    depends_on:
      - postgres
      - my_db
    volumes:
      - ./data:/data
      - ./airflow/requirements.txt:/requirements.txt
      - ./airflow/airflow.cfg:/workspaces/code-challenge/airflow/airflow.cfg
      - ./airflow/airflow.db:/workspaces/code-challenge/airflow/airflow.db
      - ./airflow/logs:/workspaces/code-challenge/airflow/logs
      - ./airflow/dags:/workspaces/code-challenge/airflow/dags
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
